version: 2

build:
  os: "ubuntu-24.04"
  tools:
    python: "3.13"
  jobs:
    post_install:
      - pip install -r module_4/docs/requirements.txt
      - export DATABASE_URL=postgresql://postgres:jhu123@localhost:5432/postgres

sphinx:
  configuration: module_4/docs/source/conf.py
  builder: html
