# .readthedocs.yaml at repo root: jhu_software_concepts/.readthedocs.yaml
version: 2

# Python environment
python:
  version: 3.13
  install:
    - method: pip
      path: module_4/docs/requirements.txt

# Environment variables (optional, but safe to have for docs)
env:
  DATABASE_URL: postgresql://postgres:jhu123@localhost:5432/postgres

# Sphinx settings
sphinx:
  configuration: module_4/docs/source/conf.py
  # Tell RTD to skip building notebooks or executing code that may fail
  builder: html
