import os
import psycopg
import psycopg_pool

pool = psycopg_pool.ConnectionPool(os.environ['DATABASE_URL'])

#Get a connection from the pool.
conn = pool.getconn()

with conn.cursor() as cur:

  cur.execute("""
    DROP TABLE IF EXISTS courses;""")

  cur.execute("""
    CREATE TABLE courses(
      id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name TEXT,
      instructor TEXT,
      room_number int
      );""")

  cur.execute("""
    INSERT INTO courses(id, name, instructor, room_number)
    VALUES(206, 'Intro to Python', 'Joe', 132), (256, 'Modern Software Concepts in Python', 'Liv', 133);""")

  conn.commit()

cur.close()
conn.close()

